### ISSUE TITLE
render collapsed

### ISSUE THREAD

**Issue by fommil** [culmat/jsTreeTable#1]
thanks so much for this great library!

I would really like my tables to be rendered collapsed... is there a way to do that using the library or must I visit all the nodes manually?

**Comment by fommil** [comment]
nevermind, `appendTreetable` seems to offer more choices in this regard

**Comment by culmat** [comment]
Hi Sam,
take a look at the _initialExpandLevel_ parameter here: http://culmat.github.io/jsTreeTable/#appendtreetable.
You can play with it here: http://culmat.github.io/jsTreeTable/doc/appendTreetable.html
Setting it to something <=1 will render inititally collapsed.

**Comment by fommil** [comment]
yup, thanks... that's what I ended up using.
