### ISSUE TITLE
Indentation 

### ISSUE THREAD

**Issue by markpmlim** [culmat/jsTreeTable#3]
I refer to your TreeTable example at the following URL:

http://culmat.github.io/jsTreeTable/doc/treeTable.html

There is very little or no indent between the root node (America) and its children North America, South America etc. This leads to a visual that seems to indicate the 2 children and its parent node are at the same (root) level. In other words, we can't tell if North and South America are in America.

On the the hand, there is sufficient indent between the non-root node (South America) and its children Argentina, Bolivia, Brazil. We can tell straightaway Argentina is in South America and Para is in Brazil.

Could the treeTable function (in treeTable.js) be modified to solve the above issue?

Thanks in advance.

**Comment by borenstein** [comment]
I believe this may be an off-by-one error on line 197. At any rate, on my website, it looked much better after I changed `15*parseInt(level-1)` to `15*parseInt(level)`. My website involves a whole lot of custom CSS, so YMMV. If it looks good on your site, too, maybe one of us ought to do a pull request.

**Comment by borenstein** [comment]
PS: I also set `data-tt-level` server-side, which wasn't in the examples. It seemed like it wasn't always right. I'm generating the entire tree on my server, then using the library to handle the expand/collapse behavior and the arrow glyph.

**Comment by markpmlim** [comment]
I have incorporated your javascript code into a Mac OS X QuickLook plugin.
